apiVersion: v1
kind: ConfigMap
metadata:
  name: siphoner-configmap
  labels:
    logagent: siphoner
data:   
   config:  |-
      SiphonFrequencySeconds: 30
      KubeEvent: false
      StdoutKeywordFilter: []
      StdoutRegexFilter: ""
      IncludeNamespaces: []
      IncludePodLabels:
         - "app=test"